apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
  - args:
    image: k8s.gcr.io/readiness 
    readinessProbe: 
    httpGet:
      host: bctw-api 
    # scheme: HTTPS 
      path: /geoserver/www/success
      port: 8080
    initialDelaySeconds: 15  
    timeoutSeconds: 1  
# oc create -f geodoc-health.yaml